export {
  _GM as GM,
  _GM_addElement as GM_addElement,
  _GM_addStyle as GM_addStyle,
  _GM_addValueChangeListener as GM_addValueChangeListener,
  _GM_cookie as GM_cookie,
  _GM_deleteValue as GM_deleteValue,
  _GM_download as GM_download,
  _GM_getResourceText as GM_getResourceText,
  _GM_getResourceURL as GM_getResourceURL,
  _GM_getTab as GM_getTab,
  _GM_getTabs as GM_getTabs,
  _GM_getValue as GM_getValue,
  _GM_info as GM_info,
  _GM_listValues as GM_listValues,
  _GM_log as GM_log,
  _GM_notification as GM_notification,
  _GM_openInTab as GM_openInTab,
  _GM_registerMenuCommand as GM_registerMenuCommand,
  _GM_removeValueChangeListener as GM_removeValueChangeListener,
  _GM_saveTab as GM_saveTab,
  _GM_setClipboard as GM_setClipboard,
  _GM_setValue as GM_setValue,
  _GM_unregisterMenuCommand as GM_unregisterMenuCommand,
  _GM_xmlhttpRequest as GM_xmlhttpRequest,
  _GM_webRequest as GM_webRequest,
  _unsafeWindow as unsafeWindow,
  _monkeyWindow as monkeyWindow,
} from './alias';

// redirect by plugin
