/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const GM: typeof import('vite-plugin-monkey/dist/client')['GM']
  const GM_addElement: typeof import('vite-plugin-monkey/dist/client')['GM_addElement']
  const GM_addStyle: typeof import('vite-plugin-monkey/dist/client')['GM_addStyle']
  const GM_addValueChangeListener: typeof import('vite-plugin-monkey/dist/client')['GM_addValueChangeListener']
  const GM_cookie: typeof import('vite-plugin-monkey/dist/client')['GM_cookie']
  const GM_deleteValue: typeof import('vite-plugin-monkey/dist/client')['GM_deleteValue']
  const GM_download: typeof import('vite-plugin-monkey/dist/client')['GM_download']
  const GM_getResourceText: typeof import('vite-plugin-monkey/dist/client')['GM_getResourceText']
  const GM_getResourceURL: typeof import('vite-plugin-monkey/dist/client')['GM_getResourceURL']
  const GM_getTab: typeof import('vite-plugin-monkey/dist/client')['GM_getTab']
  const GM_getTabs: typeof import('vite-plugin-monkey/dist/client')['GM_getTabs']
  const GM_getValue: typeof import('vite-plugin-monkey/dist/client')['GM_getValue']
  const GM_info: typeof import('vite-plugin-monkey/dist/client')['GM_info']
  const GM_listValues: typeof import('vite-plugin-monkey/dist/client')['GM_listValues']
  const GM_log: typeof import('vite-plugin-monkey/dist/client')['GM_log']
  const GM_notification: typeof import('vite-plugin-monkey/dist/client')['GM_notification']
  const GM_openInTab: typeof import('vite-plugin-monkey/dist/client')['GM_openInTab']
  const GM_registerMenuCommand: typeof import('vite-plugin-monkey/dist/client')['GM_registerMenuCommand']
  const GM_removeValueChangeListener: typeof import('vite-plugin-monkey/dist/client')['GM_removeValueChangeListener']
  const GM_saveTab: typeof import('vite-plugin-monkey/dist/client')['GM_saveTab']
  const GM_setClipboard: typeof import('vite-plugin-monkey/dist/client')['GM_setClipboard']
  const GM_setValue: typeof import('vite-plugin-monkey/dist/client')['GM_setValue']
  const GM_unregisterMenuCommand: typeof import('vite-plugin-monkey/dist/client')['GM_unregisterMenuCommand']
  const GM_webRequest: typeof import('vite-plugin-monkey/dist/client')['GM_webRequest']
  const GM_xmlhttpRequest: typeof import('vite-plugin-monkey/dist/client')['GM_xmlhttpRequest']
  const monkeyWindow: typeof import('vite-plugin-monkey/dist/client')['monkeyWindow']
  const unsafeWindow: typeof import('vite-plugin-monkey/dist/client')['unsafeWindow']
}
