name: website

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - 'website/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - '.github/workflows/website.yml'

concurrency:
  group: cloudflare-pages
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: pnpm/setup@v2

      - run: pnpm build

      - name: Deploy website
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: >-
          pnpm dlx --allow-build=sharp --allow-build=workerd wrangler@4
          pages deploy website/.vitepress/dist --project-name=vite-plugin-monkey
